language: cpp
sudo: false

notifications:
  email: false

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - build-essential
      - git-core
      - clang
      - cmake
      - lcov
      - ggcov
      - libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make